sonar.projectKey=smartcart-ai-pipeline
sonar.sources=server
sonar.tests=server/tests
sonar.test.inclusions=server/tests/**/*.js
sonar.exclusions=server/coverage/**,**/*.html,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info